title: Himpunan Peraturan NKRI
description: (V038-20210725) Himpunan Peraturan NKRI.
      This site is managed by VauLSMorg (vlsm.org) since 2020.
google_analytics: UA-89852122-7
disc: You are free to share, copy and redistribute the material of this site 
      in any medium or format for any purpose, even commercially. 
      Please give appropriate credit, provide a link to the page, 
      and indicate if changes were made. You may do so in any reasonable manner. 
      You should not apply legal terms or technological measures, 
      that legally restrict others from doing anything that is permited here.
author: Cicak Bin Kadal
show_downloads: false
theme: jekyll-theme-hacker
sitemap: true
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
social:
  name: URLs
  links:
    - https://https://github.com/rms46/uuri

# github:
#    zip_url: https://github.com/...
#    tar_url: https://github.com/...

github: [metadata]

